### ISSUE TITLE
Unable to retrieve core properties

### ISSUE THREAD

**Issue by pnehrer** [intel/openvino-rs#122]
Retrieving a non-device specific property from core results in a "general error". E.g., the following unit test fails:

```
    #[test]
    fn test_get_supported_properties() {
        let core = Core::new().unwrap();
        let supported_properties = core.get_property(PropertyKey::SupportedProperties);
        assert!(supported_properties.is_ok());
    }
```

Retrieving device-specific properties appear to be working (e.g., for CPU).

**Comment by rahulchaphalkar** [comment]
Thanks for bringing this up! Looks like official [get_property ](https://docs.openvino.ai/2024/api/c_cpp_api/group__ov__core__c__api.html#_CPPv420ov_core_get_propertyPK9ov_core_tPKcPKcPPc) (and `set_property`) function documented takes `device_name` as a parameter, so we should probably get rid of our bindings which allow no device name to be passed.

Interestingly, openvino does have 3 non-device specific properties which can be returned successfuly w/o specifying device name ([source](https://github.com/openvinotoolkit/openvino/blob/4fcfaf24b30a582477fff13e01a787e76176a495/src/inference/src/dev/core_impl.cpp#L1116)). In the current state, if you pass either `EnableMmap`, `CacheDir`, or `ForceTbbTerminate`, your test actually does pass.

However, since this is not documented, we should probably remove the option to not pass a device. @abrown what do you think?

**Comment by abrown** [comment]
> Thanks for bringing this up! Looks like official [get_property ](https://docs.openvino.ai/2024/api/c_cpp_api/group__ov__core__c__api.html#_CPPv420ov_core_get_propertyPK9ov_core_tPKcPKcPPc) (and `set_property`) function documented takes `device_name` as a parameter, so we should probably get rid of our bindings which allow no device name to be passed.

We do have `Core::get_device_property`, so let's change the parameter there to be an enum that contains only the valid property keys.

> Interestingly, openvino does have 3 non-device specific properties which can be returned successfuly w/o specifying device name ([source](https://github.com/openvinotoolkit/openvino/blob/4fcfaf24b30a582477fff13e01a787e76176a495/src/inference/src/dev/core_impl.cpp#L1116)). In the current state, if you pass either `EnableMmap`, `CacheDir`, or `ForceTbbTerminate`, your test actually does pass.

How about this: let's add an enum which contains only the three variants allowed by `Core::get_property` and use that type for the parameter.
