### ISSUE TITLE
Syntax examples

### ISSUE THREAD

**Issue by David-OConnor** [intel/openvino-rs#81]
Hi! I think an `examples` folder with one or more syntax example would help. The rust docs indicate that most functionality is based on the [Core struct](https://docs.rs/openvino/latest/openvino/struct.Core.html). It links to the [Core C++ docs](https://docs.openvino.ai/2022.3/classInferenceEngine_1_1Core.html). When I try to run methods from that page, like `GetAvailableDevices()`, or `get_available_devices()` from the Python API, the method is unrecognized. How should you, for example, list available devices in the Rust bindings? Thank you!

**Comment by abrown** [comment]
I agree. I might even prefer them as doc tests; I've done this before (e.g., [here](https://docs.rs/openvino/latest/openvino/)) but more examples would be helpful. Are you interested in helping out with this?

Re: your `GetAvailableDevices()` question, I think that is a slightly different matter: the Rust bindings are incomplete in the sense that they don't implement every possible function from OpenVINO's C API. I only initially added the functions I needed, but I am open to PRs adding more. Do you want to take a stab at it? It looks like we would need to call `ie_core_get_available_devices` and then read the returned `ie_available_devices` struct into a `Vec<String>`.

**Comment by David-OConnor** [comment]
I have a fork and am ready to get cranking. Example to start: I'd like to implement these:

```rust
use openvino::runtime::{ie_api::Model, AsyncInferQueue, Core, PartialShape};
```

Would I need to edit `openvino-sys` directly, or just `openvino`? I'm guessing both, since I can't find these other than `Core` in the openveino-sys docs.

**Comment by abrown** [comment]
Cool! I think there are a couple of things to note here:
- the `openvino-sys` crate is generated from OpenVINO's upstream C API; you can see how this is done in the [`codegen.rs`](https://github.com/intel/openvino-rs/blob/845f040a124f712afa87140cecc29b9c7a0b517f/crates/xtask/src/codegen.rs#L159) task. All of the functions you need should be in the [`generated`](https://github.com/intel/openvino-rs/tree/main/crates/openvino-sys/src/generated) folder.
- if the functions you are looking for are not there, it's probably because OpenVINO is in the process of switching to a new API, "API 2.0," which we haven't yet moved to in these bindings but you may be using in C/C++/Python. In other words, we need to shift these Rust bindings from [`ie_*`](https://github.com/openvinotoolkit/openvino/tree/master/src/bindings/c/include/c_api) to [`ov_*`](https://github.com/openvinotoolkit/openvino/tree/master/src/bindings/c/include/openvino/c); you can see more of the differences between the current API and API 2.0 [here](https://docs.openvino.ai/2022.3/openvino_2_0_inference_pipeline.html#doxid-openvino-2-0-inference-pipeline).

Can you give me an idea of whether the APIs you are looking to add are available now or only in API 2.0? If they're available now, you should be good to go to add new Rust functionality; if they're only available in API 2.0, it might be a bit of a heavy lift for you to refactor everything to use the API 2.0 and _then_ add the functionality you want. If it's that latter case, I do plan to get to the "API 2.0 refactor" but it might not happen immediately; I'm available on [Zulip](https://bytecodealliance.zulipchat.com) if you want to chat about all this.

**Comment by David-OConnor** [comment]
Great! I'm using the [OpenVINO face recognition demo](https://docs.openvino.ai/2023.1/omz_demos_face_recognition_demo_python.html).

Well, a heavily modified version of it, but the OpenVINO calls are the same. So, this should be the latest API, since I'm running OpenVINO 2023.1.0.

So, it sounds like this rust binding isn't ready for the current OpenVINO API, as the root cause perhaps.

**Comment by abrown** [comment]
> I wonder if it would be possible to use bindgen to wrap the C OpenVINO directly, without having to manually implement things. I've done that before, eg with CMSIS-DSP. But I don't know how well it would work for stuff that h as an allocator and/or C++ features. You can then wrap the results in a more rust-friendly way, like replacing pointers with refs, or just leave it.

That's essentially how these crates work: `openvino-sys` contains the bindgen-generated C API and then `openvino` wraps up those `unsafe` calls in Rust-friendly syntax. I'll revive this issue once I get to refactoring these crates to use "API 2.0."

**Comment by abrown** [comment]
@David-OConnor, it's been a while since this issue was opened; should I close it or are you still considering adding some examples?

**Comment by David-OConnor** [comment]
You can close it; I've moved on; thx!
